In [1]:
import pandas as pd

In [2]:
books = pd.read_csv("book_data.csv")

In [3]:
books.head()

,Wikipedia-article-ID,Freebase-ID,Book-title,Author,Publication-date,Book genres,Plot-summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...

In [5]:
books.dropna(subset=['Book-title', 'Author', 'Plot-summary'], inplace=True)

In [6]:
books.head()

,Wikipedia-article-ID,Freebase-ID,Book-title,Author,Publication-date,Book genres,Plot-summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...

In [7]:
books['Book genres'] = books['Book genres'].str.replace('[{}"/]', '', regex=True)

In [8]:
books.head()

,Wikipedia-article-ID,Freebase-ID,Book-title,Author,Publication-date,Book genres,Plot-summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"m016lj8: Roman \u00e0 clef, m06nbt: Satire, m0...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"m06n90: Science Fiction, m0l67h: Novella, m014...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"m02m4t: Existentialism, m02xlf: Fiction, m0pym...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"m03lrw: Hard science fiction, m06n90: Science ...",The novel posits that space around the Milky ...

In [9]:
books['tags'] = (
            (books['Author'] + ' ') * 1 +  # Lower weight for Author
            (books['Book genres'].fillna('') + ' ') * 2 +  # Medium weight for genres
            (books['Plot-summary'] + ' ') * 3  # Higher weight for summary
        ).str.lower()

In [10]:
books.head()

,Wikipedia-article-ID,Freebase-ID,Book-title,Author,Publication-date,Book genres,Plot-summary,tags
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"m016lj8: Roman \u00e0 clef, m06nbt: Satire, m0...","Old Major, the old boar on the Manor Farm, ca...","george orwell m016lj8: roman \u00e0 clef, m06n..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"m06n90: Science Fiction, m0l67h: Novella, m014...","Alex, a teenager living in near-future Englan...","anthony burgess m06n90: science fiction, m0l67..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"m02m4t: Existentialism, m02xlf: Fiction, m0pym...",The text of The Plague is divided into five p...,"albert camus m02m4t: existentialism, m02xlf: f..."
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...,david hume the argument of the enquiry proc...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"m03lrw: Hard science fiction, m06n90: Science ...",The novel posits that space around the Milky ...,"vernor vinge m03lrw: hard science fiction, m06..."

In [11]:
new_df = books[['Book-title', 'tags']].rename(columns={'Book-title': 'title'})

In [12]:
new_df

,title,tags
0,Animal Farm,"george orwell m016lj8: roman \u00e0 clef, m06n..."
1,A Clockwork Orange,"anthony burgess m06n90: science fiction, m0l67..."
2,The Plague,"albert camus m02m4t: existentialism, m02xlf: f..."
3,An Enquiry Concerning Human Understanding,david hume the argument of the enquiry proc...
4,A Fire Upon the Deep,"vernor vinge m03lrw: hard science fiction, m06..."
...,...,...
16554,Under Wildwood,"colin meloy prue mckeel, having rescued her..."
16555,Transfer of Power,"vince flynn m01jfsb: thriller, m02xlf: fiction..."
16556,Decoded,jay-z m0xdf: autobiography m0xdf: autobiograph...
16557,America Again: Re-becoming The Greatness We Ne...,stephen colbert colbert addresses topics in...
16558,Poor Folk,"fyodor dostoyevsky m02ql9: epistolary novel, m..."

In [14]:
import numpy as np
import requests
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [15]:
tfidf = TfidfVectorizer(max_features=2000, stop_words='english')

In [16]:
vectors = tfidf.fit_transform(new_df['tags']).toarray()

In [17]:
similarity = cosine_similarity(vectors)

In [18]:
similarity

array([[1.        , 0.01821254, 0.03320455, ..., 0.02790538, 0.0036092 ,
        0.04454571],
       [0.01821254, 1.        , 0.03277076, ..., 0.02138946, 0.0031356 ,
        0.03429998],
       [0.03320455, 0.03277076, 1.        , ..., 0.04352032, 0.00793427,
        0.0962304 ],
       ...,
       [0.02790538, 0.02138946, 0.04352032, ..., 1.        , 0.        ,
        0.09371471],
       [0.0036092 , 0.0031356 , 0.00793427, ..., 0.        , 1.        ,
        0.03497558],
       [0.04454571, 0.03429998, 0.0962304 , ..., 0.09371471, 0.03497558,
        1.        ]], shape=(14177, 14177))

In [19]:
new_df

,title,tags
0,Animal Farm,"george orwell m016lj8: roman \u00e0 clef, m06n..."
1,A Clockwork Orange,"anthony burgess m06n90: science fiction, m0l67..."
2,The Plague,"albert camus m02m4t: existentialism, m02xlf: f..."
3,An Enquiry Concerning Human Understanding,david hume the argument of the enquiry proc...
4,A Fire Upon the Deep,"vernor vinge m03lrw: hard science fiction, m06..."
...,...,...
16554,Under Wildwood,"colin meloy prue mckeel, having rescued her..."
16555,Transfer of Power,"vince flynn m01jfsb: thriller, m02xlf: fiction..."
16556,Decoded,jay-z m0xdf: autobiography m0xdf: autobiograph...
16557,America Again: Re-becoming The Greatness We Ne...,stephen colbert colbert addresses topics in...
16558,Poor Folk,"fyodor dostoyevsky m02ql9: epistolary novel, m..."

In [20]:
new_df[new_df['title']=="Transfer of Power"].index[0]

np.int64(16555)

In [21]:
new_df[new_df['title']=="The Plague"].index[0]

np.int64(2)

In [22]:
distance = sorted(list(enumerate(similarity[2])), reverse=True, key=lambda vectors:vectors[1])
for i in distance[0:5]:
    print(new_df.iloc[i[0]].title)

The Plague
Gregor and the Curse of the Warmbloods
The Octagonal Raven
Forest Mage
The Alchymist's Cat

In [24]:
def recommend(books):
    index=new_df[new_df['title']==books].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vectors:vectors[1])
    for i in distance[0:5]:
        print(new_df.iloc[i[0]].title)

In [25]:
recommend("The Plague")

The Plague
Gregor and the Curse of the Warmbloods
The Octagonal Raven
Forest Mage
The Alchymist's Cat

In [29]:
distance = sorted(list(enumerate(similarity[14176])), reverse=True, key=lambda vectors:vectors[1])
for i in distance[0:5]:
    print(new_df.iloc[i[0]].title)

Poor Folk
Keep the Aspidistra Flying
Voyage in the Dark
Anna Karenina
In the Country of Last Things

In [30]:
import pickle

In [31]:
pickle.dump(new_df, open('book_list.pkl', 'wb'))

In [32]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [34]:
pickle.load(open('book_list.pkl', 'rb'))

,title,tags
0,Animal Farm,"george orwell m016lj8: roman \u00e0 clef, m06n..."
1,A Clockwork Orange,"anthony burgess m06n90: science fiction, m0l67..."
2,The Plague,"albert camus m02m4t: existentialism, m02xlf: f..."
3,An Enquiry Concerning Human Understanding,david hume the argument of the enquiry proc...
4,A Fire Upon the Deep,"vernor vinge m03lrw: hard science fiction, m06..."
...,...,...
16554,Under Wildwood,"colin meloy prue mckeel, having rescued her..."
16555,Transfer of Power,"vince flynn m01jfsb: thriller, m02xlf: fiction..."
16556,Decoded,jay-z m0xdf: autobiography m0xdf: autobiograph...
16557,America Again: Re-becoming The Greatness We Ne...,stephen colbert colbert addresses topics in...
16558,Poor Folk,"fyodor dostoyevsky m02ql9: epistolary novel, m..."